### ISSUE TITLE
Fix typos

### ISSUE THREAD

**Issue by shuamiller** [TheOdinProject/ruby_testing#15]
Spec files 11a_shared_example_spec.rb, 11b_cat_spec.rb, and 11c_dog_spec.rb all have typos on lines 5, 8, and 8 respectively where, I believe, 15 should read 11. I believe, spec file 12_magic_seven_spec.rb is missing the word 'what' on line 52.

**Comment by rlmoser99** [comment]
@shuamiller Thank you for taking the time to submit this issue. I have submitted a PR with the typos that I could find with your issue. Since the line numbers are different in the three 11 files, I am not sure I know what you meant by lines 5 and 8.

Please take a look at the PR #16 and let me know if I am missing something. 

If you find any more typos in this repo, you can submit a PR with these changes, rather than try to describe them. Either fork the repo, just the the contribution instructions for TOP or you can update the files on directly on github.

**Comment by rlmoser99** [comment]
Closing this issue, as I believe PR #16 resolves it. 

@shuamiller If this does not fully address it, please submit a PR or open another issue with specific details on the typos.
